version: '3.9'

services:
  web:
    build: .
    container_name: inventory_web
    security_opt:
      - apparmor:unconfined
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --timeout 120
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - db_volume:/app/db
    env_file:
      - .env
    ports:
      - "11000:8000"   # 👈 important (expose to host)
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  db_volume:
